#Definition Namespace für alle Ressourcen
apiVersion: v1
kind: Namespace
metadata:
  name: JSVAR_NAMESPACE
---  
apiVersion: batch/v1
kind: Job
metadata:
  name: jdatabaseuc
  namespace: JSVAR_NAMESPACE
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: jdatabaseuc
        image: JSVAR_DOCKERIMAGE
        args:
        - /bin/bash
        - -c
        - /opt/gcSession.sh JSVAR_UC_DBNAME JSVAR_UC_DBUSER JSVAR_UC_DBPSWD
      restartPolicy: Never
